### ISSUE TITLE
Rewrite feature parity tracker

### ISSUE THREAD

**Issue by lucypoulton** [TheDeveloperDen/DevDenBot#42]
**Commands**
- [x] Colour role
- [x] Daily reward
- [x] FAQ
- [x] Hot take
- [x] Info
- [x] Leaderboard
- [x] Learning
- [x] Paste
- [x] Pastify
- [x] Role
- [x] Set
- [x] Timeout
- [x] XP

**Listeners**
- [x] Ask to ask
- [x] FAQ commands
- [x] Join/leave
- [x] Language status
- [x] ~~Message logger~~ Image forwarding to audit log
- [x] Pastify
- [x] Showcase auto reaction
- [x] Token scanner
- [x] Hot take (automatic)
- [x] XP

**Comment by lucypoulton** [comment]
just need to fix bm's xp refactory stuff
